spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/fis_2021_gongjung
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
   
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

# 2022-02-25 이승범 : 이미지 파일 경로 저장을 위한 include
  profiles:
    include:
      - config

# 2022-03-03 현승구 : 에러 메시지 추가
  messages:
    basename: errors

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.Type: trace
#    org.apache.coyote.http11: debug
    #package fis_solution.PMproject.service.UploadService: debug

# 이승범  세션 1시간 유지
server:
  servlet:
    session:
      timeout: 3600
